### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by IrishBruse**
These are the changes i made to the UI as i found there was some inconsistencies and extra borders than needed.

image
image
image
image

Also added custom scrollbars as the base windows one looks very out of place
image

### CODE REVIEW

**Comment by deepnight** [comment]
I posted some PR guidelines here: 
https://github.com/deepnight/ldtk/wiki

**Comment by deepnight** [comment]
I'm not exactly sure to understand the changes your screenshots are point at. The only I spotted was the background of the "anchor" button on a "folder of rules".

Could you provide a quick example of what was actually fixed?

**Comment by IrishBruse** [comment]
here is what it looks like before the additions
image

image

image

image

image

**Comment by deepnight** [comment]
Very clear! Thank you for the explanations and your PR :)

**Pull request merged**
