### PR TITLE
Add F_File type

### PR DESCRIPTION
**Pull request by Yanrishatum**
* Added `F_File` type to properties. Acts exactly the same way as `F_String` with extra flavor of file select and extension filters.
* Redid entity instance editor a bit and implemented the stretch bar on the side, allowing user to manually resize it. Because 200 pixels is very little.

Considerations:
* Ideally F_File should validate text field to check that file exists and not an absolute path, but I'm not sure how to implement it.
* Currently stretch size is not retained, and probably should be saved in the editor config?

### CODE REVIEW

**Comment by deepnight** [comment]
Thank you! If possible, next time, try to separate features (one PR per new feature) 😄

**Comment by deepnight** [comment]
A few remarks after some testing: 

 - the naming might be confusing: it's not an actual file, but a file path
 - the existence of the file isn't checked, which is kind of unexpected UX behavior
 - when adding extensions, the typed string isn't cleaned up, and can contain various junks, like spaces, or even invalid characters. Every time something is typed and used by the editor, it should be cleaned up first ;)

**Comment by deepnight** [comment]
I'll update/fix a few things

**Comment by Yanrishatum** [comment]
> If possible, next time, try to separate features 

I usually do separate features, it's just this time they overlapped, and separating them was a bit of a pain. :) 

> the existence of the file isn't checked, which is kind of unexpected UX behavior

As mentioned - I'm not sure how to implement it. I don't want to enforce that file 100% exists, but I'd like to at least make a warning sign that would indicate that "hey, this file does not exists!"

> Every time something is typed and used by the editor, it should be cleaned up first ;)

I do clean it up in `setAcceptFileTypes` thought? Maybe not completely, but I do perform trimming at the very least.

**Comment by deepnight** [comment]
I understand for feats separation :) No worry!

Yes, the file existence should only be softly checked here. Some warning, and even an optional flag to disable this check in the field def 🤔 It needs some testing to get that right & balanced.

Yes I didn't check the method itself! I will probably update it with a regex which is a little bit more robust, and which will also allow any character separator for the user.

By the way, when a value is nullable (like `acceptFileTypes`) it should be declared as such (ie. `Null< Array<String> >`) as a doc/reminder. *Future-me* has a short memory and often checks var declarations for nullables ;)

**Comment by deepnight** [comment]
Tested regex here: 
https://regex101.com/r/UpHErw/1

**Pull request merged**
